language: node_js

sudo: required
dist: trusty

env:
  global:
    - SUPPRESS_NO_CONFIG_WARNING=true
    - PERSONAL_ACCESS_TOKEN=TEST_TOKEN

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache # includes bowers cache

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --pure-lockfile
  - ./node_modules/bower/bin/bower install --config.interactive=false

script:
  - yarn test:cover

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
